package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.DockerCommandStep
import jetbrains.buildServer.configs.kotlin.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'hello_app_build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("hello_app_build")) {
    expectSteps {
        script {
            name = "Set Commit ID"
            id = "Set_Commit_ID"
            scriptContent = """
                SHORT_COMMIT_HASH=${'$'}(git rev-parse --short HEAD)
                echo "##teamcity[setParameter name='env.COMMIT_ID' value='${'$'}SHORT_COMMIT_HASH']"
                echo "commit-id = ${'$'}SHORT_COMMIT_HASH"
            """.trimIndent()
        }
        dockerCommand {
            name = "dockerbuild"
            id = "dockerbuild"
            commandType = build {
                source = file {
                    path = "Dockerfile"
                }
                contextDir = "."
                platform = DockerCommandStep.ImagePlatform.Linux
                namesAndTags = """
                    088332244542.dkr.ecr.ap-south-1.amazonaws.com/non-prod/hello-app:%teamcity.build.branch%_%build.number%
                    088332244542.dkr.ecr.ap-south-1.amazonaws.com/non-prod/hello-app:%teamcity.build.branch%_latest
                """.trimIndent()
                commandArgs = "--platform linux/amd64 --build-arg artifact_version=%env.COMMIT_ID% --build-arg build_version=%build.counter%"
            }
        }
        dockerCommand {
            name = "docker image push"
            id = "docker_image_push"
            commandType = push {
                namesAndTags = """
                    088332244542.dkr.ecr.ap-south-1.amazonaws.com/non-prod/hello-app:%teamcity.build.branch%_%build.number%
                    088332244542.dkr.ecr.ap-south-1.amazonaws.com/non-prod/hello-app:%teamcity.build.branch%_latest
                """.trimIndent()
                removeImageAfterPush = false
            }
        }
        step {
            name = "DeployDev"
            id = "DeployDev"
            type = "octopus.create.release"
            param("octopus_space_name", "OASIS")
            param("octopus_channel_name", "Development")
            param("octopus_host", "http://10.29.1.84")
            param("octopus_project_name", "hello-app")
            param("octopus_deployto", "Development")
            param("secure:octopus_apikey", "******")
            param("octopus_releasenumber", "%build.number%")
        }
        step {
            name = "DeployStage"
            id = "DeployStage"
            type = "octopus.create.release"
            param("octopus_space_name", "OASIS")
            param("octopus_channel_name", "Stage")
            param("octopus_host", "http://10.29.1.84")
            param("octopus_project_name", "hello-app")
            param("octopus_deployto", "Stage")
            param("secure:octopus_apikey", "******")
            param("octopus_releasenumber", "%build.number%")
        }
        step {
            name = "DeployUAT"
            id = "DeployUAT"
            type = "octopus.create.release"
            param("octopus_space_name", "OASIS")
            param("octopus_channel_name", "Uat")
            param("octopus_host", "http://10.29.1.84")
            param("octopus_project_name", "hello-app")
            param("octopus_deployto", "Uat")
            param("secure:octopus_apikey", "******")
            param("octopus_releasenumber", "%build.number%")
        }
        script {
            name = "Retag_UAT_image_for_Prod"
            id = "Retag_release_branch_image_for_Prod"
            scriptContent = """
                docker pull 088332244542.dkr.ecr.ap-south-1.amazonaws.com/non-prod/hello-app:uat_latest
                docker tag 088332244542.dkr.ecr.ap-south-1.amazonaws.com/non-prod/hello-app:uat_latest 088332244542.dkr.ecr.ap-south-1.amazonaws.com/prod/hello-app:prod_%build.number%
                docker tag 088332244542.dkr.ecr.ap-south-1.amazonaws.com/non-prod/hello-app:uat_latest 088332244542.dkr.ecr.ap-south-1.amazonaws.com/prod/hello-app:prod_latest
            """.trimIndent()
        }
        dockerCommand {
            name = "Push_Prod_image"
            id = "Push_Prod_image"
            commandType = push {
                namesAndTags = """
                    088332244542.dkr.ecr.ap-south-1.amazonaws.com/prod/hello-app:prod_%build.number%
                    088332244542.dkr.ecr.ap-south-1.amazonaws.com/prod/hello-app:prod_latest
                """.trimIndent()
                removeImageAfterPush = false
            }
        }
    }
    steps {
        update<BuildStep>(3) {
            clearConditions()

            conditions {
                equals("teamcity.build.branch", "main")
                doesNotEqual("env.isProdBuild", "Yes")
            }
            param("secure:octopus_apikey", "credentialsJSON:48da93a8-8fcc-49f0-9a35-dd8b8dfb06e8")
        }
        update<BuildStep>(4) {
            clearConditions()

            conditions {
                equals("teamcity.build.branch", "stage")
                doesNotEqual("env.isProdBuild", "Yes")
            }
            param("secure:octopus_apikey", "credentialsJSON:48da93a8-8fcc-49f0-9a35-dd8b8dfb06e8")
        }
        update<BuildStep>(5) {
            clearConditions()

            conditions {
                equals("teamcity.build.branch", "uat")
                doesNotEqual("env.isProdBuild", "Yes")
            }
            param("secure:octopus_apikey", "credentialsJSON:48da93a8-8fcc-49f0-9a35-dd8b8dfb06e8")
        }
    }
}
